---
title: 'Zitat-R'
subtitle: ''
author: 'fnaufel'
email: 'https://fnaufel.github.io/'
date: '`r Sys.Date()`'
lang: 'en'
# TODO: include LaTeX fields
output: 
  html_document:
    theme: readable
    highlight: tango
    css: file:///home/fnaufel/RMarkdown/Template01/styles.css
    toc: true
    toc_depth: 2
    number_sections: true
    fig_width: 7
    fig_height: 5
    fig_caption: true
    df_print: kable
    # code_folding: show
    self_contained: true
    # keep_md: true
    # includes:
    #   in_header: header.html
    #   before_body: doc_prefix.html
    #   after_body: doc_suffix.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center')

#library()
library(gt)

library(tidyverse)
theme_set(
  theme_linedraw() +
    theme(
      axis.line = element_blank(),
      panel.border = element_blank(),
      panel.grid.minor = element_blank()
    )
)
```


# Reading the myclippings file

```{r}
join_lines <- function(x, pos, df) {
  
  # # If first line, delete those 3 extraneous chars
  # NOT NECESSARY!
  # if (pos == 1) {
  #   x[1] <- str_sub(x[1], 4)
  # }

  # First line: 
  # <book> (<author>)
  # or only <book> followed by a space
  line   <- str_match(x[1], '^(.+)[ ](?:\\(([^)]+)\\))?$')
  book   <- line[1, 2]
  author <- line[1, 3]

  # Second line:
  # - <type> <position> | Added on <datetime>
  line     <- str_match(x[2], '^- ([^ ]+) ([^|]+)\\| Added on (.+)$')
  type    <- line[1, 2]
  # Sometimes position is 'on Page n'
  position <- str_trim(line[1, 3]) %>% str_remove('^on ')
  datetime <- line[1, 4]
  
  # Third line: empty

  # Fourth line:
  # If empty, NA
  quote <- str_trim(x[4])
  if (quote == '') 
    quote <- NA

  # Fifth line: ==========

  # If first record
  if (pos == 1) {
    df <- tibble(
      book = book,
      author = author,
      type = type,
      position = position,
      when = datetime,
      quote = quote
    )
  } else {
    df <- df %>% 
      add_row(
        book = book,
        author = author,
        type = type,
        position = position,
        when = datetime,
        quote = quote
      )
  }
  
  # Return
  df
  
}
```

```{r}
df <- tibble(.rows = 0)

df <- read_lines_chunked(
  'Examples/MyClippings-2011-04-30.txt',
  AccumulateCallback$new(join_lines, df),
  chunk_size = 5
)
```

```{r}
glimpse(df)
```


```{r}
head(df)
```


# Clean the data

* Split position into unit, begin, end. It may happen that begin == end. Careful with situations like 4315-19.

* Mutate when into datetime.

